/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as HomeRouteImport } from './routes/home'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WellnessIndexRouteImport } from './routes/wellness/index'
import { Route as CircleIndexRouteImport } from './routes/circle/index'
import { Route as WellnessTrendsRouteImport } from './routes/wellness/trends'
import { Route as WellnessBreatheRouteImport } from './routes/wellness/breathe'
import { Route as SettingsThresholdsRouteImport } from './routes/settings/thresholds'
import { Route as SettingsPrivacyRouteImport } from './routes/settings/privacy'
import { Route as SettingsNotificationsRouteImport } from './routes/settings/notifications'
import { Route as SettingsDataSourcesRouteImport } from './routes/settings/data-sources'
import { Route as SettingsConnectionRouteImport } from './routes/settings/connection'
import { Route as OnboardingWearablesRouteImport } from './routes/onboarding/wearables'
import { Route as OnboardingVerifyRouteImport } from './routes/onboarding/verify'
import { Route as OnboardingCircleRouteImport } from './routes/onboarding/circle'
import { Route as CircleLaunchRouteImport } from './routes/circle/launch'
import { Route as CircleAddRouteImport } from './routes/circle/add'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WellnessIndexRoute = WellnessIndexRouteImport.update({
  id: '/wellness/',
  path: '/wellness/',
  getParentRoute: () => rootRouteImport,
} as any)
const CircleIndexRoute = CircleIndexRouteImport.update({
  id: '/circle/',
  path: '/circle/',
  getParentRoute: () => rootRouteImport,
} as any)
const WellnessTrendsRoute = WellnessTrendsRouteImport.update({
  id: '/wellness/trends',
  path: '/wellness/trends',
  getParentRoute: () => rootRouteImport,
} as any)
const WellnessBreatheRoute = WellnessBreatheRouteImport.update({
  id: '/wellness/breathe',
  path: '/wellness/breathe',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsThresholdsRoute = SettingsThresholdsRouteImport.update({
  id: '/thresholds',
  path: '/thresholds',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsPrivacyRoute = SettingsPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsDataSourcesRoute = SettingsDataSourcesRouteImport.update({
  id: '/data-sources',
  path: '/data-sources',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsConnectionRoute = SettingsConnectionRouteImport.update({
  id: '/connection',
  path: '/connection',
  getParentRoute: () => SettingsRoute,
} as any)
const OnboardingWearablesRoute = OnboardingWearablesRouteImport.update({
  id: '/onboarding/wearables',
  path: '/onboarding/wearables',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingVerifyRoute = OnboardingVerifyRouteImport.update({
  id: '/onboarding/verify',
  path: '/onboarding/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingCircleRoute = OnboardingCircleRouteImport.update({
  id: '/onboarding/circle',
  path: '/onboarding/circle',
  getParentRoute: () => rootRouteImport,
} as any)
const CircleLaunchRoute = CircleLaunchRouteImport.update({
  id: '/circle/launch',
  path: '/circle/launch',
  getParentRoute: () => rootRouteImport,
} as any)
const CircleAddRoute = CircleAddRouteImport.update({
  id: '/circle/add',
  path: '/circle/add',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/messages': typeof MessagesRoute
  '/settings': typeof SettingsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/team': typeof TeamRoute
  '/circle/add': typeof CircleAddRoute
  '/circle/launch': typeof CircleLaunchRoute
  '/onboarding/circle': typeof OnboardingCircleRoute
  '/onboarding/verify': typeof OnboardingVerifyRoute
  '/onboarding/wearables': typeof OnboardingWearablesRoute
  '/settings/connection': typeof SettingsConnectionRoute
  '/settings/data-sources': typeof SettingsDataSourcesRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/privacy': typeof SettingsPrivacyRoute
  '/settings/thresholds': typeof SettingsThresholdsRoute
  '/wellness/breathe': typeof WellnessBreatheRoute
  '/wellness/trends': typeof WellnessTrendsRoute
  '/circle/': typeof CircleIndexRoute
  '/wellness/': typeof WellnessIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/messages': typeof MessagesRoute
  '/settings': typeof SettingsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/team': typeof TeamRoute
  '/circle/add': typeof CircleAddRoute
  '/circle/launch': typeof CircleLaunchRoute
  '/onboarding/circle': typeof OnboardingCircleRoute
  '/onboarding/verify': typeof OnboardingVerifyRoute
  '/onboarding/wearables': typeof OnboardingWearablesRoute
  '/settings/connection': typeof SettingsConnectionRoute
  '/settings/data-sources': typeof SettingsDataSourcesRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/privacy': typeof SettingsPrivacyRoute
  '/settings/thresholds': typeof SettingsThresholdsRoute
  '/wellness/breathe': typeof WellnessBreatheRoute
  '/wellness/trends': typeof WellnessTrendsRoute
  '/circle': typeof CircleIndexRoute
  '/wellness': typeof WellnessIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/messages': typeof MessagesRoute
  '/settings': typeof SettingsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/team': typeof TeamRoute
  '/circle/add': typeof CircleAddRoute
  '/circle/launch': typeof CircleLaunchRoute
  '/onboarding/circle': typeof OnboardingCircleRoute
  '/onboarding/verify': typeof OnboardingVerifyRoute
  '/onboarding/wearables': typeof OnboardingWearablesRoute
  '/settings/connection': typeof SettingsConnectionRoute
  '/settings/data-sources': typeof SettingsDataSourcesRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/privacy': typeof SettingsPrivacyRoute
  '/settings/thresholds': typeof SettingsThresholdsRoute
  '/wellness/breathe': typeof WellnessBreatheRoute
  '/wellness/trends': typeof WellnessTrendsRoute
  '/circle/': typeof CircleIndexRoute
  '/wellness/': typeof WellnessIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/messages'
    | '/settings'
    | '/sitemap.xml'
    | '/team'
    | '/circle/add'
    | '/circle/launch'
    | '/onboarding/circle'
    | '/onboarding/verify'
    | '/onboarding/wearables'
    | '/settings/connection'
    | '/settings/data-sources'
    | '/settings/notifications'
    | '/settings/privacy'
    | '/settings/thresholds'
    | '/wellness/breathe'
    | '/wellness/trends'
    | '/circle/'
    | '/wellness/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/messages'
    | '/settings'
    | '/sitemap.xml'
    | '/team'
    | '/circle/add'
    | '/circle/launch'
    | '/onboarding/circle'
    | '/onboarding/verify'
    | '/onboarding/wearables'
    | '/settings/connection'
    | '/settings/data-sources'
    | '/settings/notifications'
    | '/settings/privacy'
    | '/settings/thresholds'
    | '/wellness/breathe'
    | '/wellness/trends'
    | '/circle'
    | '/wellness'
  id:
    | '__root__'
    | '/'
    | '/home'
    | '/messages'
    | '/settings'
    | '/sitemap.xml'
    | '/team'
    | '/circle/add'
    | '/circle/launch'
    | '/onboarding/circle'
    | '/onboarding/verify'
    | '/onboarding/wearables'
    | '/settings/connection'
    | '/settings/data-sources'
    | '/settings/notifications'
    | '/settings/privacy'
    | '/settings/thresholds'
    | '/wellness/breathe'
    | '/wellness/trends'
    | '/circle/'
    | '/wellness/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRoute: typeof HomeRoute
  MessagesRoute: typeof MessagesRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TeamRoute: typeof TeamRoute
  CircleAddRoute: typeof CircleAddRoute
  CircleLaunchRoute: typeof CircleLaunchRoute
  OnboardingCircleRoute: typeof OnboardingCircleRoute
  OnboardingVerifyRoute: typeof OnboardingVerifyRoute
  OnboardingWearablesRoute: typeof OnboardingWearablesRoute
  WellnessBreatheRoute: typeof WellnessBreatheRoute
  WellnessTrendsRoute: typeof WellnessTrendsRoute
  CircleIndexRoute: typeof CircleIndexRoute
  WellnessIndexRoute: typeof WellnessIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wellness/': {
      id: '/wellness/'
      path: '/wellness'
      fullPath: '/wellness/'
      preLoaderRoute: typeof WellnessIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/circle/': {
      id: '/circle/'
      path: '/circle'
      fullPath: '/circle/'
      preLoaderRoute: typeof CircleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wellness/trends': {
      id: '/wellness/trends'
      path: '/wellness/trends'
      fullPath: '/wellness/trends'
      preLoaderRoute: typeof WellnessTrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wellness/breathe': {
      id: '/wellness/breathe'
      path: '/wellness/breathe'
      fullPath: '/wellness/breathe'
      preLoaderRoute: typeof WellnessBreatheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/thresholds': {
      id: '/settings/thresholds'
      path: '/thresholds'
      fullPath: '/settings/thresholds'
      preLoaderRoute: typeof SettingsThresholdsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/privacy': {
      id: '/settings/privacy'
      path: '/privacy'
      fullPath: '/settings/privacy'
      preLoaderRoute: typeof SettingsPrivacyRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/notifications': {
      id: '/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/data-sources': {
      id: '/settings/data-sources'
      path: '/data-sources'
      fullPath: '/settings/data-sources'
      preLoaderRoute: typeof SettingsDataSourcesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/connection': {
      id: '/settings/connection'
      path: '/connection'
      fullPath: '/settings/connection'
      preLoaderRoute: typeof SettingsConnectionRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/onboarding/wearables': {
      id: '/onboarding/wearables'
      path: '/onboarding/wearables'
      fullPath: '/onboarding/wearables'
      preLoaderRoute: typeof OnboardingWearablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/verify': {
      id: '/onboarding/verify'
      path: '/onboarding/verify'
      fullPath: '/onboarding/verify'
      preLoaderRoute: typeof OnboardingVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/circle': {
      id: '/onboarding/circle'
      path: '/onboarding/circle'
      fullPath: '/onboarding/circle'
      preLoaderRoute: typeof OnboardingCircleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/circle/launch': {
      id: '/circle/launch'
      path: '/circle/launch'
      fullPath: '/circle/launch'
      preLoaderRoute: typeof CircleLaunchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/circle/add': {
      id: '/circle/add'
      path: '/circle/add'
      fullPath: '/circle/add'
      preLoaderRoute: typeof CircleAddRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SettingsRouteChildren {
  SettingsConnectionRoute: typeof SettingsConnectionRoute
  SettingsDataSourcesRoute: typeof SettingsDataSourcesRoute
  SettingsNotificationsRoute: typeof SettingsNotificationsRoute
  SettingsPrivacyRoute: typeof SettingsPrivacyRoute
  SettingsThresholdsRoute: typeof SettingsThresholdsRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsConnectionRoute: SettingsConnectionRoute,
  SettingsDataSourcesRoute: SettingsDataSourcesRoute,
  SettingsNotificationsRoute: SettingsNotificationsRoute,
  SettingsPrivacyRoute: SettingsPrivacyRoute,
  SettingsThresholdsRoute: SettingsThresholdsRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRoute: HomeRoute,
  MessagesRoute: MessagesRoute,
  SettingsRoute: SettingsRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TeamRoute: TeamRoute,
  CircleAddRoute: CircleAddRoute,
  CircleLaunchRoute: CircleLaunchRoute,
  OnboardingCircleRoute: OnboardingCircleRoute,
  OnboardingVerifyRoute: OnboardingVerifyRoute,
  OnboardingWearablesRoute: OnboardingWearablesRoute,
  WellnessBreatheRoute: WellnessBreatheRoute,
  WellnessTrendsRoute: WellnessTrendsRoute,
  CircleIndexRoute: CircleIndexRoute,
  WellnessIndexRoute: WellnessIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
